version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: dance_user
      POSTGRES_PASSWORD: dance_password
      POSTGRES_DB: dance_platform_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: